# Generated by Django 3.2.8 on 2023-08-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessowner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitiveexamdata',
            name='chapter',
            field=models.CharField(max_length=50, verbose_name='Chapters'),
        ),
    ]
