# Generated by Django 3.2.8 on 2023-08-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessowner', '0002_alter_competitiveexamdata_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitiveexamdata',
            name='time_per_subject',
        ),
    ]
