# Generated by Django 3.2.8 on 2023-08-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessowner', '0003_remove_competitiveexamdata_time_per_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiveexamdata',
            name='time_per_subject',
            field=models.FloatField(blank=True, null=True, verbose_name='Time-Per-Subject'),
        ),
    ]
