# Generated by Django 3.2.8 on 2023-08-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessowner', '0004_competitiveexamdata_time_per_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicquestions',
            name='time_duration',
        ),
        migrations.RemoveField(
            model_name='competitivequestions',
            name='time_duration',
        ),
        migrations.AlterField(
            model_name='academicexamdata',
            name='chapter',
            field=models.CharField(max_length=50, verbose_name='Chapters'),
        ),
    ]
