# Generated by Django 3.2.8 on 2023-08-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessowner', '0005_auto_20230822_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicquestions',
            name='time_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitivequestions',
            name='time_duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
