# Generated by Django 3.2.8 on 2023-08-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessowner', '0006_auto_20230822_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicexamdata',
            name='chapter',
            field=models.CharField(max_length=50, verbose_name='AcademicChapters'),
        ),
    ]
