# Generated by Django 3.2.8 on 2023-08-29 11:01

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('businessowner', '0009_academicexamdata_time_per_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiveexams',
            name='question_set',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='businessowner.competitivequestions'),
        ),
    ]
