# Generated by Django 3.2.8 on 2023-09-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessowner', '0011_academicexams_question_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessowners',
            name='is_plan_purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
