# Generated by Django 3.2.8 on 2023-09-04 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessowner', '0013_businessnewses'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessnewses',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_batch', to='businessowner.competitivebatches'),
        ),
        migrations.AddField(
            model_name='businessnewses',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_standard', to='businessowner.academicstandards'),
        ),
        migrations.AddField(
            model_name='students',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='selected_institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute_select', to='businessowner.businessowners'),
        ),
    ]
