# Generated by Django 3.2.8 on 2023-09-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessowner', '0015_termsandpolicy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicexams',
            options={'verbose_name_plural': '8. Academic Exams'},
        ),
        migrations.AlterModelOptions(
            name='competitiveexams',
            options={'verbose_name_plural': '7. Competitive Exams'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name_plural': '9. Students'},
        ),
        migrations.AlterModelOptions(
            name='termsandpolicy',
            options={'verbose_name_plural': '6. Terms And Policy'},
        ),
        migrations.AddField(
            model_name='students',
            name='selected_language',
            field=models.CharField(choices=[('english', 'english'), ('gujarati', 'gujarati')], default='english', max_length=50, verbose_name='selected_language'),
        ),
    ]
