# Generated by Django 3.2.8 on 2023-09-30 05:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('businessowner', '0016_auto_20230918_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_answer', models.CharField(max_length=50)),
                ('academic_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_acade', to='businessowner.academicboards')),
                ('academic_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_acade', to='businessowner.academicquestions')),
                ('competitive_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_comp', to='businessowner.competitiveexams')),
                ('competitive_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_comp', to='businessowner.competitivequestions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answer', to='businessowner.students')),
            ],
        ),
    ]
