# Generated by Django 3.2.8 on 2023-10-21 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessowner', '0017_auto_20231007_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessowners',
            name='is_reset',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
        migrations.CreateModel(
            name='WebsocketRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=10)),
                ('academic_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_room', to='businessowner.academicexams')),
                ('competitive_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitive_room', to='businessowner.competitiveexams')),
            ],
        ),
    ]
