# Generated by Django 3.2.8 on 2023-10-27 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessowner', '0018_auto_20231021_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicquestions',
            name='academic_question_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_image', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='competitivequestions',
            name='competitive_question_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_image', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
