# Generated by Django 3.2.8 on 2023-11-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessowner', '0020_results_time_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswers',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
